name: eslint in pull request
on: pull_request
jobs:
  eslint:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: yarn lint
